language: python

python:
  - "3.7"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind -y
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=asn1tools setup.py test
  - make test-sdist
  - (cd examples/benchmarks/packages && wget https://github.com/ANSSI-FR/pycrate/archive/master.zip && unzip -qq master.zip)
  - env PYTHONPATH=.:examples/benchmarks/packages/pycrate-master python examples/benchmarks/packages/ber.py
  - env PYTHONPATH=.:examples/benchmarks/packages/pycrate-master python examples/benchmarks/packages/uper.py
  - env PYTHONPATH=. python examples/benchmarks/codecs.py
  - env PYTHONPATH=. python examples/benchmarks/question/question.py
  - env PYTHONPATH=. python examples/hello_world.py
  - env PYTHONPATH=. python examples/x509_pem.py
  - env PYTHONPATH=. python examples/compact_extensions_uper/main.py
  - env PYTHONPATH=. python examples/programming_types/main.py
  - if [[ "$(python --version)" =~ "Python 3" ]] ; then make test-c ; fi
  - make -C examples/benchmarks/c_source

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy

before_deploy:
  - git clean -dfx

deploy:
  provider: pypi
  username: __token__
  password:
    secure: "TS9+4GlHLopJRB9OqF9snx1sOnAIZ+vws6Wei9nB7Wm4QFN99KuTzXwy3S1M05JhFwoqHIHQ6Dwa5CPha5ozOr89LjpHJhy9sCy5wP5n5XXwnuf16rQ11dm2wnYRQR87AXmvLYGrhWaB4rWnKl6mCJUMB/a0hNfLoNHF1W7YB15uDBWnYAfk7ZdzPrTJg1vvs7YHD1Wldpu/gxj9DpAlpFjsRioiYxA/ebvyWN00iOy4XTE2RQBNZgulOUoyv3EtXdFtoNVUwTzA881V/ct9eLI26qVODtK18nysGUAlNbBQpmifUTCNoG0x6NpKWBkeDO7sGrJVdI0ZpeO0xkRgRrY/qKW3UTHl4NrNoB3QqOGNcOc7MWJNAJnFTOl2SSA6AIl7AMBanf5zyNRgbGSESBCSp3vTONGWA7NJZgezbx/QKJ9Vre/9Kz6xFVnt+UJcC3wuhnd4r/LKXx7gKsQmXF55Tg/VDGQ61UIo/q0C5ktKq/H19NZ6tZ9x2tSulc/HGhKYwlJS2317bbSTVhKG7KtFgwvtjexO9H2zC9HbiAK4vIBK8lXQCskWBifCZfwZdtwm5YWz8+Tz0DcydAVPdGcVN5QRJ3cKYKo5Hb08o1ObwJdMMggMoPLsgvLQ/UNF1OKrP4/TyMgQXz8R9oauOKOKhexrHq7pflm56xx0Pi4="
  edge: true
  skip_existing: true
  on:
    tags: true
